#!/usr/bin/python3
"""Folder colour as its OWN icon theme.   tools/folder_theme.py <Papirus|Papirus-Dark|…> <colour>   -> prints the theme name
Relinking the folder icons inside Papirus (tools/folder_color.sh) changes files under an unchanged theme NAME: running apps
keep their cached pictures (Dolphin showed the old folders until it was restarted). A derived theme with its own name,
  ~/.local/share/icons/Glass-<base>-<colour>   (Inherits=<base>; only the "places" folders, as links to <base>'s coloured files)
makes a colour switch a real icon-theme change, which every toolkit reloads properly. Built once per base + colour."""
import configparser, os, re, sys
base, colour = sys.argv[1], sys.argv[2]
roots = [os.path.expanduser("~/.local/share/icons"), "/usr/share/icons"]
src = next((os.path.join(r, base) for r in roots if os.path.isfile(os.path.join(r, base, "index.theme"))), None)
if not src: sys.exit("no such icon theme: " + base)
name = "Glass-%s-%s" % (base, colour); dst = os.path.join(roots[0], name)
stamp = os.path.join(dst, ".glass-built")
VERSION = "3"   # 2 was a partial theme (only places) that inherited the base: it caught other icons through name fallback
if os.path.isfile(stamp) and open(stamp).read().strip() == VERSION + " " + colour and os.path.getmtime(stamp) >= os.path.getmtime(os.path.join(src, "index.theme")): print(name); sys.exit(0)
# A FULL mirror of the base theme, not a partial theme that inherits it: KDE's icon lookup tries an icon's shorter fallback
# names ("network-wired-symbolic" -> "network-wired" -> "network") inside the FIRST theme before it asks the parents, so a
# theme holding only folder icons (it has "network", "user-desktop", …) turned the shell's Ethernet, Bluetooth and
# show-desktop symbols into folders. Here every directory of the base is present: all but "places" as ONE link to the
# base's directory, "places" as a real folder that links every file of the base, the coloured ones to the new colour.
import shutil
index_src = os.path.join(src, "index.theme")
ini = configparser.RawConfigParser(strict=False); ini.optionxform = str; ini.read(index_src, encoding="utf-8")
if os.path.isdir(dst): shutil.rmtree(dst)
os.makedirs(dst)
made = 0
for d in [x for x in ini.sections() if x != "Icon Theme"]:
    sd = os.path.join(src, d)
    if not os.path.isdir(sd): continue
    real = os.path.realpath(sd); od = os.path.join(dst, d)
    os.makedirs(os.path.dirname(od), exist_ok=True)
    if not d.endswith("/places"):
        if not os.path.lexists(od): os.symlink(real, od)
        continue
    def final(name, hops=0):                                              # follow links INSIDE this folder to the real file's name
        q = os.path.join(real, name)
        if hops > 8 or not os.path.islink(q): return name
        t = os.readlink(q)
        return final(t, hops + 1) if "/" not in t else name
    cur = re.sub(r"^folder-|\.svg$", "", final("folder.svg"))              # the colour the base theme uses now (folder-blue.svg -> blue)
    os.makedirs(od, exist_ok=True)
    for f in os.listdir(real):
        target = os.path.join(real, f)
        if cur and cur != "folder" and os.path.islink(target):
            r_ = final(f)                                                 # folder-blue.svg, folder-blue-games.svg, user-blue-home.svg, …; also via inode-directory -> folder.svg
            if re.search(r"-%s(-|\.svg$)" % re.escape(cur), r_):
                want = re.sub(r"-%s(?=-|\.svg$)" % re.escape(cur), "-" + colour, r_, count=1)
                if os.path.isfile(os.path.join(real, want)): target = os.path.join(real, want); made += 1
        os.symlink(target, os.path.join(od, f))
if not made: shutil.rmtree(dst, ignore_errors=True); sys.exit("colour not available in %s: %s" % (base, colour))
text = open(index_src, encoding="utf-8").read()
text = re.sub(r"(?m)^Name=.*$", "Name=" + name, text, count=1)
text = re.sub(r"(?m)^Name\[[^\]]*\]=.*\n", "", text)
text = re.sub(r"(?m)^Comment=.*$", "Comment=%s with %s folders (generated by Glass Desktop)" % (base, colour), text, count=1)
open(os.path.join(dst, "index.theme"), "w", encoding="utf-8").write(text)
open(stamp, "w").write(VERSION + " " + colour + "\n")
print(name)
