#!/usr/bin/python3
"""Folder colour as its OWN icon theme.   tools/folder_theme.py <Papirus|Papirus-Dark|…> <colour>   -> prints the theme name
Relinking the folder icons inside Papirus (tools/folder_color.sh) changes files under an unchanged theme NAME: running apps
keep their cached pictures (Dolphin showed the old folders until it was restarted). A derived theme with its own name,
  ~/.local/share/icons/Glass-<base>-<colour>   (Inherits=<base>; only the "places" folders, as links to <base>'s coloured files)
makes a colour switch a real icon-theme change, which every toolkit reloads properly. Built once per base + colour."""
import configparser, os, re, sys
base, colour = sys.argv[1], sys.argv[2]
roots = [os.path.expanduser("~/.local/share/icons"), "/usr/share/icons"]
src = next((os.path.join(r, base) for r in roots if os.path.isfile(os.path.join(r, base, "index.theme"))), None)
if not src: sys.exit("no such icon theme: " + base)
name = "Glass-%s-%s" % (base, colour); dst = os.path.join(roots[0], name)
stamp = os.path.join(dst, ".glass-built")
VERSION = "2"   # 1 missed most links (folder-blue-games, user-blue-home, inode-directory -> folder)
if os.path.isfile(stamp) and open(stamp).read().strip() == VERSION + " " + colour and os.path.getmtime(stamp) >= os.path.getmtime(os.path.join(src, "index.theme")): print(name); sys.exit(0)
ini = configparser.RawConfigParser(strict=False); ini.optionxform = str; ini.read(os.path.join(src, "index.theme"), encoding="utf-8")
dirs = [d for d in ini.sections() if d.endswith("/places") and os.path.isdir(os.path.join(src, d))]
made = 0; out_dirs = []
for d in dirs:
    sd = os.path.realpath(os.path.join(src, d)); links = {}
    def final(name, hops=0):                                              # follow links INSIDE this folder to the real file's name
        q = os.path.join(sd, name)
        if hops > 8 or not os.path.islink(q): return name
        t = os.readlink(q)
        return final(t, hops + 1) if "/" not in t else name
    cur = re.sub(r"^folder-|\.svg$", "", final("folder.svg"))              # the colour the base theme uses now (folder-blue.svg -> blue)
    if not cur or cur == "folder": continue
    for f in os.listdir(sd):
        if not os.path.islink(os.path.join(sd, f)): continue
        real = final(f)                                                   # folder-blue.svg, folder-blue-games.svg, user-blue-home.svg, …; also via inode-directory -> folder.svg
        if not re.search(r"-%s(-|\.svg$)" % re.escape(cur), real): continue
        want = re.sub(r"-%s(?=-|\.svg$)" % re.escape(cur), "-" + colour, real, count=1)
        if os.path.isfile(os.path.join(sd, want)): links[f] = os.path.join(sd, want)
    if not links: continue
    od = os.path.join(dst, d); os.makedirs(od, exist_ok=True); out_dirs.append(d)
    for f, target in links.items():
        lp = os.path.join(od, f)
        if os.path.lexists(lp): os.remove(lp)
        os.symlink(target, lp); made += 1
if not made: sys.exit("colour not available in %s: %s" % (base, colour))
with open(os.path.join(dst, "index.theme"), "w") as fh:
    fh.write("[Icon Theme]\nName=%s\nComment=%s with %s folders (generated by Glass Desktop)\nInherits=%s,breeze,hicolor\nDirectories=%s\n" % (name, base, colour, base, ",".join(out_dirs)))
    for d in out_dirs:
        fh.write("\n[%s]\n" % d + "".join("%s=%s\n" % kv for kv in ini.items(d)))
open(stamp, "w").write(VERSION + " " + colour + "\n")
print(name)
