#!/usr/bin/env python3
"""tokens.json -> KDE pieces: a colour scheme (Glass.colors) and the settings of the Darkly widget style + decoration.
Interim step of roadmap item 2: Darkly is the closest existing style; a token-driven fork replaces it later.
Writes to build/kde/. Nothing is installed here — see tools/apply_kde.sh."""
import json, pathlib, re, sys
root = pathlib.Path(__file__).resolve().parent.parent
VARIANT = sys.argv[1] if len(sys.argv) > 1 else "dark"            # dark -> Glass.colors, light -> GlassLight.colors
NAME = "Glass" if VARIANT == "dark" else "GlassLight"
t = json.loads((root / "design" / "tokens.json").read_text()); d = t[VARIANT]; g = dict(t["glass"])
if VARIANT == "light": g["tintApp"] = g.get("tintAppLight", g["tintApp"]); g["contentOpacity"] = g.get("contentOpacityLight", g.get("contentOpacity", 1.0))
out = root / "build" / "kde"; out.mkdir(parents=True, exist_ok=True)
def rgb(c):
    c = c.strip()
    if c.startswith("#"): return tuple(int(c[i:i+2], 16) for i in (1, 3, 5))
    m = re.match(r"rgba?\(([^)]+)\)", c); parts = [x.strip() for x in m.group(1).split(",")]
    return tuple(int(float(x)) for x in parts[:3])
def alpha(c):
    m = re.match(r"rgba\(([^)]+)\)", c.strip()); return float(m.group(1).split(",")[3]) if m else 1.0
s = lambda c: ",".join(map(str, rgb(c)))
def group(name, bg, alt, fg=d["text"]):
    return f"""[Colors:{name}]
BackgroundAlternate={s(alt)}
BackgroundNormal={s(bg)}
DecorationFocus={s(d['focusSolid'])}
DecorationHover={s(d['focusSolid'])}
ForegroundActive={s(d['text'])}
ForegroundInactive={s(d['textDim'])}
ForegroundLink={s(d['link'])}
ForegroundNegative={s(d['negative'])}
ForegroundNeutral={s(d['warning'])}
ForegroundNormal={s(fg)}
ForegroundPositive={s(d['positive'])}
ForegroundVisited={s(d['textDim'])}
"""
chrome_a = int(round(alpha(g["tintApp"]) * 255))
# Selection as GLASS, not a grey slab: translucent white over whatever is underneath (frosted sidebar, solid view), the same
# tile the shell uses. KColorScheme keeps the alpha, so Kirigami highlights and the widget style both get it.
sel_a = int(round(alpha(d["selected"]) * 255))
selection = group('Selection', d['selectionSolid'], d['selectionSolid']).replace(
    f"BackgroundNormal={s(d['selectionSolid'])}", f"BackgroundNormal={s(d['selected'])},{sel_a}").replace(
    f"BackgroundAlternate={s(d['selectionSolid'])}", f"BackgroundAlternate={s(d['selected'])},{sel_a}")
colors = f"""# Generated by glass-desktop/tools/gen_kde.py from design/tokens.json — do not edit by hand.
[ColorEffects:Disabled]
Color={"56,56,56" if VARIANT == "dark" else "200,200,200"}
ColorAmount=0
ColorEffect=0
ContrastAmount=0.65
ContrastEffect=1
IntensityAmount=0.1
IntensityEffect=2

[ColorEffects:Inactive]
ChangeSelectionColor=false
Color=112,111,110
ColorAmount=0.025
ColorEffect=2
ContrastAmount=0.1
ContrastEffect=2
Enable=false
IntensityAmount=0
IntensityEffect=0

{group('Button', d['card'], d['sidebar'])}
{group('Complementary', d['sidebar'], d['window'])}
{group('Header', d['header'], d['window'])}
{group('Header][Inactive', d['header'], d['window'])}
{selection}
{group('Tooltip', d['card'], d['sidebar'])}
{group('View', d['view'], d['window'])}
{group('Window', d['window'], d['sidebar'])}
[General]
ColorScheme={NAME}
Name={NAME}
shadeSortColumn=true

[KDE]
contrast=4

[WM]
activeBackground={s(d['header'])},{chrome_a}
activeBlend={s(d['text'])}
activeForeground={s(d['text'])}
inactiveBackground={s(d['header'])},{chrome_a}
inactiveBlend={s(d['textDim'])}
inactiveForeground={s(d['textDim'])}
"""
(out / f"{NAME}.colors").write_text(colors)
chrome = int(round(alpha(g["tintApp"]) * 100))
# Darkly: decoration corner radius on Wayland = OtherCornerRadius * 2
darkly = {
  "Common": {"CornerRadius": t["radius"]["control"],
             "ShadowStrength": t["decoration"].get("shadowStrengthLight" if VARIANT == "light" else "shadowStrength", 41),
             "ShadowSize": t["decoration"].get("shadowSizeLight" if VARIANT == "light" else "shadowSize", "ShadowLarge")},
  "Style": {"DolphinSidebarOpacity": chrome, "DolphinViewOpacity": int(round(g.get("contentOpacity", 1.0) * 100)), "GlassContentOpacity": int(round(g.get("contentOpacity", 1.0) * 100)), "TransparentDolphinView": "false", "ToolBarOpacity": chrome, "MenuBarOpacity": chrome,
            "TabBarOpacity": chrome, "MenuOpacity": chrome, "SidePanelDrawFrame": "false", "ToolBarDrawSeparator": "false", "FancyMargins": "false"},
  "Windeco": {"OtherCornerRadius": t["radius"]["window"] // 2, "TitleAlignment": "AlignCenter", "ButtonSize": "ButtonDefault", "DrawTitleBarSeparator": "false", "DrawBackgroundGradient": "false",
              "GlassTitleBarHeight": t["spacing"]["titlebarHeight"], "GlassDotSize": t["decoration"]["buttonSize"], "GlassTitleBarOpacity": chrome, "GlassOutlineActive": t["decoration"].get("outlineActive", 96), "GlassOutlineInactive": t["decoration"].get("outlineInactive", 44),
              "GlassOutlineWidthActive": int(round(t["decoration"].get("outlineWidthActive", 1.6) * 10)), "GlassOutlineWidthInactive": int(round(t["decoration"].get("outlineWidthInactive", 1.0) * 10)),
              "GlassFocusGlow": str(bool(t["decoration"].get("focusGlow", False))).lower()},
}
(out / ("darkly.json" if VARIANT == "dark" else "darkly-light.json")).write_text(json.dumps(darkly, indent=2))
print("wrote", out / f"{NAME}.colors", "and", out / "darkly.json", f"(chrome opacity {chrome} %)")
