#!/usr/bin/env python3
"""tokens.json -> GTK. One stylesheet body, emitted twice:
  build/gtk/gtk-4.0.css  for GTK 4 / libadwaita (named colours + CSS variables + shape rules)
  build/gtk/gtk-3.0.css  for GTK 3 on top of the adw-gtk3 base theme (same named colours, GTK 3 selectors)
libadwaita ignores GTK themes by design; what it does honour is the user stylesheet, so that is where the look goes."""
import json, pathlib, re
root = pathlib.Path(__file__).resolve().parent.parent
import sys
VARIANT = sys.argv[1] if len(sys.argv) > 1 else "dark"            # light writes gtk-*-light.css
SUF = "" if VARIANT == "dark" else "-light"
t = json.loads((root / "design" / "tokens.json").read_text()); d, r, dec = t[VARIANT], t["radius"], t["decoration"]
out = root / "build" / "gtk"; out.mkdir(parents=True, exist_ok=True)
A = lambda a: f"alpha({'white' if VARIANT == 'dark' else 'black'}, {a})"
colors = {
  "accent_color": d["focusSolid"], "accent_bg_color": d["accent"], "accent_fg_color": d["accentText"],
  "destructive_color": d["negative"], "destructive_bg_color": d["negative"], "destructive_fg_color": "#ffffff",
  "success_color": d["positive"], "success_bg_color": d["positive"], "success_fg_color": d["accentText"],
  "warning_color": d["warning"], "warning_bg_color": d["warning"], "warning_fg_color": d["accentText"],
  "error_color": d["negative"], "error_bg_color": d["negative"], "error_fg_color": "#ffffff",
  "window_bg_color": d["window"], "window_fg_color": d["text"], "view_bg_color": d["view"], "view_fg_color": d["text"],
  "headerbar_bg_color": d["header"], "headerbar_fg_color": d["text"], "headerbar_border_color": d["separator"],
  "headerbar_backdrop_color": d["window"], "headerbar_shade_color": "rgba(0,0,0,0.25)", "headerbar_darker_shade_color": "rgba(0,0,0,0.4)",
  "sidebar_bg_color": d["sidebar"], "sidebar_fg_color": d["text"], "sidebar_backdrop_color": d["window"], "sidebar_shade_color": "rgba(0,0,0,0.25)", "sidebar_border_color": d["separator"],
  "secondary_sidebar_bg_color": d["window"], "secondary_sidebar_fg_color": d["text"], "secondary_sidebar_backdrop_color": d["window"], "secondary_sidebar_shade_color": "rgba(0,0,0,0.25)", "secondary_sidebar_border_color": d["separator"],
  "card_bg_color": d["card"], "card_fg_color": d["text"], "card_shade_color": "rgba(0,0,0,0.3)",
  "dialog_bg_color": d["sidebar"], "dialog_fg_color": d["text"], "popover_bg_color": d["card"], "popover_fg_color": d["text"], "popover_shade_color": "rgba(0,0,0,0.3)",
  "thumbnail_bg_color": d["card"], "thumbnail_fg_color": d["text"], "shade_color": "rgba(0,0,0,0.3)", "scrollbar_outline_color": "rgba(0,0,0,0.5)",
}
head = "/* Generated by glass-desktop/tools/gen_gtk.py from design/tokens.json — do not edit by hand. */\n"
defs = "".join(f"@define-color {k} {v};\n" for k, v in colors.items())
root_vars = ":root {\n" + "".join(f"  --{k.replace('_', '-')}: {v};\n" for k, v in colors.items()) + f"  --window-radius: {r['window']}px;\n}}\n"
hot = {"close": d["negative"], "maximize": d["positive"], "minimize": d["warning"]}
dot = dec["buttonSize"]
common = f"""
/* selection = a small pane of glass: translucent fill + lit hairline rim */
row:selected, .navigation-sidebar row:selected, treeview.view:selected, iconview:selected, flowboxchild:selected {{
  background-color: {A(0.16)}; color: {d['text']}; box-shadow: inset 0 0 0 1px {A(0.20)}; border-radius: {r['control']}px; }}
row:hover:not(:selected), .navigation-sidebar row:hover:not(:selected) {{ background-color: {A(0.06)}; border-radius: {r['control']}px; }}
selection, *:selected selection {{ background-color: {A(0.28)}; color: {d['text']}; }}
separator, .sidebar-pane separator {{ background-color: {A(0.07)}; min-width: 1px; min-height: 1px; }}
button, entry, spinbutton, combobox button, dropdown button, menubutton button {{ border-radius: {r['control']}px; }}
entry, spinbutton {{ background-color: alpha(black, 0.28); box-shadow: inset 0 0 0 1px {A(0.08)}; }}
entry:focus-within, spinbutton:focus-within {{ box-shadow: inset 0 0 0 1px {A(0.45)}; outline: none; }}
switch {{ border-radius: 999px; background-color: {A(0.14)}; }}
switch:checked {{ background-color: {d['accent']}; }}
switch slider {{ border-radius: 999px; background-color: #ffffff; }}
switch:checked slider {{ background-color: {d['accentText']}; }}
scale trough {{ background-color: {A(0.16)}; border-radius: 3px; min-height: 6px; }}
scale highlight {{ background-color: {d['accent']}; border-radius: 3px; }}
scale slider {{ background-color: #ffffff; border-radius: 999px; }}
progressbar trough {{ background-color: {A(0.14)}; border-radius: 3px; }}
progressbar progress {{ background-color: {d['accent']}; border-radius: 3px; }}
checkbutton check:checked, checkbutton radio:checked, check:checked, radio:checked {{ background-color: {d['accent']}; color: {d['accentText']}; }}
popover > contents, popover.background > contents, menu, .menu, .context-menu {{ border-radius: {r['card']}px; box-shadow: inset 0 0 0 1px {A(0.10)}; }}
/* menu rows: the same small pane of glass as every other hover / selection */
menu menuitem:hover, .menu menuitem:hover, .context-menu menuitem:hover, popover.menu modelbutton:hover, popover modelbutton:hover, popover.menu row:hover {{
  background-color: {A(0.14)}; box-shadow: inset 0 0 0 1px {A(0.18)}; border-radius: {r['control']}px; color: {d['text']}; }}
menubar > menuitem:hover, menubar > item:hover, .menubar > menuitem:hover {{ background-color: {A(0.13)}; box-shadow: inset 0 0 0 1px {A(0.18)}; border-radius: {r['control']}px; color: {d['text']}; }}
tooltip {{ border-radius: {r['control']}px; background-color: alpha({d['card']}, 0.96); box-shadow: inset 0 0 0 1px {A(0.10)}; }}
link, button.link {{ color: {d['link']}; }}
"""
def controls(sel, gtk3=False):   # window buttons: glyph-free dots, colour-coded under the pointer (same as the KWin decoration)
    # Which node is the dot differs per toolkit, and getting it wrong changes the size:
    #  GTK 3: the BUTTON node (adw-gtk3 pads the image, a dot on the image came out ~22 px),
    #  GTK 4: the IMAGE node (libadwaita stretches the button to the header's height, a dot on the button became a tall pill).
    if gtk3:
        n, img = sel, f"{sel} > image"
        s = f"""
{sel} {{ min-width: {dot}px; min-height: {dot}px; padding: 0; margin: 0 {dec['buttonGap'] // 2 + 2}px; border: none; border-radius: 999px; box-shadow: none; outline: none;
  background-image: none; background-color: {A(0.17)}; color: transparent; -gtk-icon-shadow: none; text-shadow: none; }}
{img} {{ min-width: 0; min-height: 0; padding: 0; margin: 0; opacity: 0; -gtk-icon-source: none; background: none; }}
"""
    else:
        n = f"{sel} image"
        s = f"""
{sel} {{ min-width: {dot}px; min-height: {dot}px; padding: 0; margin: 0 {dec['buttonGap'] // 2 + 2}px; background: none; box-shadow: none; border: none; outline: none; }}
{sel} image {{ min-width: {dot}px; min-height: {dot}px; border-radius: 999px; background-color: {A(0.17)}; color: transparent; -gtk-icon-source: none; padding: 0; margin: 0; }}
"""
    pre = lambda cls, state="": (f"{sel}{cls}{state}" if gtk3 else f"{sel}{cls}{state} image")
    s += f"{pre('.close')} {{ background-color: {A(0.36)}; }}\n{pre('', ':backdrop')} {{ background-color: {A(0.09)}; }}\n{pre('.close', ':backdrop')} {{ background-color: {A(0.14)}; }}\n"
    for k, c in hot.items(): s += f"{pre('.' + k, ':hover')} {{ background-color: {c}; }}\n{pre('.' + k, ':active')} {{ background-color: shade({c}, 0.85); }}\n"
    return s
gtk4 = head + defs + root_vars + common + controls("windowcontrols button") + f"""
window.csd {{ border-radius: {r['window']}px; box-shadow: 0 0 0 1px {A(0.24)}, 0 18px 50px alpha(black, 0.55); }}
/* same shadow GEOMETRY focused and unfocused: a client-side shadow that changes size makes the surface resize on every
   focus switch (Firefox visibly glitched). Only the strengths differ. */
window.csd:backdrop {{ box-shadow: 0 0 0 1px {A(0.11)}, 0 18px 50px alpha(black, 0.40); }}
windowcontrols {{ border-spacing: 0; margin: 0 1px; }}
headerbar {{ min-height: {t['spacing']['titlebarHeight']}px; box-shadow: inset 0 -1px {A(0.06)}; }}
headerbar .title, windowtitle .title {{ font-weight: {t['font']['weightTitle']}; }}
.card, list.boxed-list {{ border-radius: {r['card']}px; box-shadow: inset 0 0 0 1px {A(0.08)}; }}
button.suggested-action {{ background-color: {d['accent']}; color: {d['accentText']}; }}
button.pill {{ border-radius: 999px; }}
"""
gtk3 = head + defs + common + controls("headerbar button.titlebutton", gtk3=True) + controls(".titlebar button.titlebutton", gtk3=True) + f"""
decoration {{ border-radius: {r['window']}px; box-shadow: 0 0 0 1px {A(0.24)}, 0 18px 50px alpha(black, 0.55); }}
decoration:backdrop {{ box-shadow: 0 0 0 1px {A(0.11)}, 0 18px 50px alpha(black, 0.40); }}
window.csd, window.csd > .titlebar, headerbar {{ border-top-left-radius: {r['window']}px; border-top-right-radius: {r['window']}px; }}
headerbar {{ min-height: {t['spacing']['titlebarHeight']}px; box-shadow: inset 0 -1px {A(0.06)}; background-image: none; background-color: {d['header']}; }}
headerbar .title {{ font-weight: {t['font']['weightTitle']}; }}
button.suggested-action {{ background-image: none; background-color: {d['accent']}; color: {d['accentText']}; }}
"""
(out / f"gtk-4.0{SUF}.css").write_text(gtk4); (out / f"gtk-3.0{SUF}.css").write_text(gtk3)
print("wrote", out / f"gtk-4.0{SUF}.css", len(gtk4), "bytes and", out / "gtk-3.0.css", len(gtk3), "bytes")
